name: raspberry-pi-node-gpio
base: core18
version: '0.0.2'
summary: Control Raspberry Pi GPIO Pins With Node On Ubuntu Core 18
description: |
  This boilerplate snap shows how to control the GPIO pins of a raspberry pi
  running Ubuntu Core 18 with a snap that follows strict confinement.

grade: devel
confinement: strict

architectures:
  - build-on: arm64
    run-on: arm64

apps:
  # init-scripts:
  #   command: bin/connect-gpio.sh
  #   daemon: oneshot #runs this command once at startup
  #   plugs: 
  #     - gpio
  main:
    command: main
    plugs:
      - network-bind
      - gpio
parts:
  raspberry-pi-node-gpio:
    source: .
    plugin: nodejs
  scripts:
    source: ./scripts
    plugin: dump